default_context:
  project_name: 'Walk Doggers'
  project_slug: 'walk-doggers-api'
  domain_main: 'walkdoggers.club'
  domain_staging: 'stag.walkdoggers.club'
  docker_swarm_stack_name_main: 'walkdoggers-club'
  docker_swarm_stack_name_staging: 'stag-walkdoggers-club'
  secret_key: '6b26da56087f6635901552e2d4b3f443ebcf8f783e0b547b5450a9915590d18b'
  first_superuser: 'admin@walkdoggers.club'
  first_superuser_password: '12345678'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.walkdoggers.club", "https://stag.walkdoggers.club", "https://walkdoggers.club", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@walkdoggers.club'
  postgres_password: '12345678'
  pgadmin_default_user: 'admin@walkdoggers.club'
  pgadmin_default_user_password: '12345678'
  traefik_constraint_tag: 'walkdoggers.club'
  traefik_constraint_tag_staging: 'stag.walkdoggers.club'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345678'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
