version: "3.3"

services:
  db:
    image: postgres:12
    volumes:
      - db-data-postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  db-mongo:
    image: mongo
    volumes:
      - db-data-mongo:/data/db
    ports:
      - "27017-27019:27017-27019"
    container_name: walk-doggers-mongodb

  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - db
      - db-mongo
    ports:
      - 80:80
    volumes:
      - ./:/app
    env_file:
      - .env
    command: /start-reload.sh


volumes:
  db-data-postgres:

  db-data-mongo:
