name: CI gh actions test
on:
  push:
    branches:
      - test-github-actions
    paths-ignore:
      - "README.md"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          repository: tpo-2020-2021/LP234-21
          ref: dev

      - name: Create default .env file for api
        working-directory: ./src/walk-doggers-api/
        run: cp default.env .env

      - name: Start API and databases with docker-compose
        working-directory: ./src/walk-doggers-api/
        run: docker-compose up -d

      - name: Run npm install for app
        working-directory: ./src/walk-doggers-app/
        run: npm install

      - name: Start Expo app web server with docker run command
        working-directory: ./src/walk-doggers-app/
        run: docker run -d -it --rm -p 19000-19010:19000-19010 -v "$PWD:/app" -e EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 --name=walk-doggers-expo-web kerbe/expo start:web

      - name: Install npm wait-on
        run: sudo npm install wait-on -g

      - name: wait-on page and echo hello and print page html
        run: wait-on http://localhost:19006/ && echo hello && curl http://localhost:19006/
